name: AntiCheat
main: Salus\Main
version: 1.0
api: [3.0.0-ALPHA5]
author: Driesboy
description: AntiCheat for MCPE
api: [3.0.0-ALPHA5,3.0.0-ALPHA6]
permissions:
    salus:
        description: "Allows to use all salus features."
        default: false
        children:
            salus.legitop:
                description: "A permission."
                default: false