---
##########################
#  / _\ __ _| |_   _ ___ #
#  \ \ / _` | | | | / __|#
#  _\ \ (_| | | |_| \__ \#
#  \__/\__,_|_|\__,_|___/#
##########################

# Max amount of warns before punishment
max-warns: 3

#######################################################
#Enabled punishment : - Ban                           #
#                     - IPBan                         #
#                     - MegaBan (IPBan and Ban in one)#
#                     - Command                       #
#######################################################
punishment: Command

#Enabled after you use Command in the line above
punishment-command:
  - "nban %PLAYER% 1week You are banned for %REASON% by %SENDER%"

warn-command:
  - "kick %PLAYER% You are warned for %REASON% by %SENDER%"

##########################################################
#  _____                                           _     #
# /  __ \                                         | |    #
# | /  \/ ___  _ __ ___  _ __ ___   __ _ _ __   __| |___ #
# | |    / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|#
# | \__/\ (_) | | | | | | | | | | | (_| | | | | (_| \__ \#
#  \____/\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/#
##########################################################

ReportCommand: true

VanishCommand: true

WarnCommand: true

###########################################################
#  ____ _           _   _____             _             _ #
#/  __ \ |         | | /  __ \           | |           | |#
#| /  \/ |__   __ _| |_| /  \/ ___  _ __ | |_ _ __ ___ | |#
#| |   | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |#
#| \__/\ | | | (_| | |_| \__/\ (_) | | | | |_| | | (_) | |#
# \____/_| |_|\__,_|\__|\____/\___/|_| |_|\__|_|  \___/|_|#
###########################################################
perWorldChat: true

AntiSpam: true

#time in seconds a player has to wait to send a message again
time: 1
#max warnings a player will receive until they receive a kick
max_warnings: 2
#warn player each time they spam
warning_message: "§ePlease stop chatting too quick! You may be kicked for spamming! §cWarnings:§6 %warns%"
#message that will be sent if player is spamming
#%player% = players name
kick_reason: "§aYou have been kicked for spamming"

NoAds: true

##############################################################################################################
# _   _           _       _        ___  _   _        _ _           _            ______          _        _   #
#| | | |         | |     | |      / _ \| | | |      (_) |         | |           | ___ \        | |      | |  #
#| | | |_ __   __| | __ _| |_ ___/ /_\ \ |_| |_ _ __ _| |__  _   _| |_ ___  ___ | |_/ /_ _  ___| | _____| |_ #
#| | | | '_ \ / _` |/ _` | __/ _ \  _  | __| __| '__| | '_ \| | | | __/ _ \/ __||  __/ _` |/ __| |/ / _ \ __|#
#| |_| | |_) | (_| | (_| | ||  __/ | | | |_| |_| |  | | |_) | |_| | ||  __/\__ \| | | (_| | (__|   <  __/ |_ #
# \___/| .__/ \__,_|\__,_|\__\___\_| |_/\__|\__|_|  |_|_.__/ \__,_|\__\___||___/\_|  \__,_|\___|_|\_\___|\__|#
#      | |                                                                                                   #
#      |_|                                                                                                   #
##############################################################################################################
detect-UpdateAttributesPacket: true

###################################################################################
#______                        _____                     ___  ___          _      #
#|  ___|                      |  __ \                    |  \/  |         | |     #
#| |_ ___  _ __ ___ ___ ______| |  \/ __ _ _ __ ___   ___| .  . | ___   __| | ___ #
#|  _/ _ \| '__/ __/ _ \______| | __ / _` | '_ ` _ \ / _ \ |\/| |/ _ \ / _` |/ _ \#
#| || (_) | | | (_|  __/      | |_\ \ (_| | | | | | |  __/ |  | | (_) | (_| |  __/#
#\_| \___/|_|  \___\___|       \____/\__,_|_| |_| |_|\___\_|  |_/\___/ \__,_|\___|#
###################################################################################
detect-ForceGameMode: true

#################
# ______ _      #
#|  ___| |      #
#| |_  | |_   _ #
#|  _| | | | | |#
#| |   | | |_| |#
#\_|   |_|\__, |#
#          __/ |#
#         |___/ #
#################
detect-FlyPackets: true

detect-Fly: true

##############################
#______                _     #
#| ___ \              | |    #
#| |_/ /___  __ _  ___| |__  #
#|    // _ \/ _` |/ __| '_ \ #
#| |\ \  __/ (_| | (__| | | |#
#\_| \_\___|\__,_|\___|_| |_|#
##############################
detect-Reach: true

############################################
#______                        ___________ #
#|  ___|                      |  _  | ___ \#
#| |_ ___  _ __ ___ ___ ______| | | | |_/ /#
#|  _/ _ \| '__/ __/ _ \______| | | |  __/ #
#| || (_) | | | (_|  __/      \ \_/ / |    #
#\_| \___/|_|  \___\___|       \___/\_|    #
############################################
detect-ForceOP: true

#####################################
# _   _             _____ _ _       #
#| \ | |           /  __ \ (_)      #
#|  \| | ___ ______| /  \/ |_ _ __  #
#| . ` |/ _ \______| |   | | | '_ \ #
#| |\  | (_) |     | \__/\ | | |_) |#
#\_| \_/\___/       \____/_|_| .__/ #
#                            | |    #
#                            |_|    #
#####################################
#BETA!!!
detect-NoClip: true

#DO NOT CHANGE THIS
config-version: 1.4
